name: rapids
channels:
- rapidsai
- rapidsai-nightly
- conda-forge
- nvidia
dependencies:
- cudatoolkit=CUDA_VER
- cudf=RAPIDS_VER
- numpy>=NUMPY_VER
- cupy
- pynvml
- ucx-proc=*=gpu
- ucx-py=UCX_PY_VER
