name: Check for gpuCI updates

on:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00” UTC
  workflow_dispatch:

jobs:
  update-gpuci:
    runs-on: ubuntu-latest
    if: github.repository == 'rapidsai/dask-build-environment'

    steps:
      - uses: actions/checkout@v4

      - name: Fetch current RAPIDS versions from build matrix
        id: parse_yaml
        uses: the-coding-turtle/ga-yaml-parser@v0.1.2
        with:
          file: .github/workflows/build.yml
          export_to_envs: false
          return_to_outputs: true

      - name: Get old RAPIDS / UCX-Py versions
        env:
          OLD_RAPIDS_VER: ${{ steps.parse_yaml.outputs.jobs_docker_strategy_matrix_rapids_0 }}
          RAPIDS_VER: ${{ steps.parse_yaml.outputs.jobs_docker_strategy_matrix_rapids_1 }}
        run: |
          echo OLD_RAPIDS_VER=$OLD_RAPIDS_VER >> $GITHUB_ENV
          echo OLD_UCX_PY_VER=$(curl -sL https://version.gpuci.io/rapids/$OLD_RAPIDS_VER) >> $GITHUB_ENV
          echo RAPIDS_VER=$RAPIDS_VER >> $GITHUB_ENV
          echo UCX_PY_VER=$(curl -sL https://version.gpuci.io/rapids/$RAPIDS_VER) >> $GITHUB_ENV

      - name: Get latest cuDF nightly version
        id: cudf_latest
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "rapidsai-nightly"
          package: "cudf"
          version_system: "CalVer"

      - name: Get latest UCX-Py nightly version
        id: ucx_py_latest
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "rapidsai-nightly"
          package: "ucx-py"
          version_system: "CalVer"

      - name: Strip git tags from versions
        env:
          FULL_RAPIDS_VER: ${{ steps.cudf_latest.outputs.version }}
          FULL_UCX_PY_VER: ${{ steps.ucx_py_latest.outputs.version }}
        run: |
          echo "NEW_RAPIDS_VER=$(echo $FULL_RAPIDS_VER | cut -d'.' -f1,2)" >> $GITHUB_ENV
          echo "NEW_UCX_PY_VER=$(echo $FULL_UCX_PY_VER | cut -d'.' -f1,2)" >> $GITHUB_ENV

      - name: Update new RAPIDS versions
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "${{ env.RAPIDS_VER }}"
          replace: "${{ env.NEW_RAPIDS_VER }}"
          regex: false

      - name: Update old RAPIDS versions
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "${{ env.OLD_RAPIDS_VER }}"
          replace: "${{ env.RAPIDS_VER }}"
          regex: false

      - name: Update new UCX-Py versions
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "${{ env.UCX_PY_VER }}"
          replace: "${{ env.NEW_UCX_PY_VER }}"
          regex: false

      - name: Update old UCX-Py versions
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "${{ env.OLD_UCX_PY_VER }}"
          replace: "${{ env.UCX_PY_VER }}"
          regex: false

      - name: Create pull request
        if: ${{ env.RAPIDS_VER != env.NEW_RAPIDS_VER && env.UCX_PY_VER != env.NEW_UCX_PY_VER }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update gpuCI `RAPIDS_VER` to `${{ env.NEW_RAPIDS_VER }}`, `UCX_PY_VER` to `${{ env.NEW_UCX_PY_VER }}`"
          title: "Update gpuCI `RAPIDS_VER` to `${{ env.NEW_RAPIDS_VER }}`"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: "upgrade-gpuci-rapids"
          body: |
            New cuDF and ucx-py nightly versions have been detected.

            Updated `dask.yaml` and `run.sh` to use `RAPIDS_VER=${{ env.NEW_RAPIDS_VER }}` and `UCX_PY_VER=${{ env.NEW_UCX_PY_VER }}`.
